INPUT:
  MIN_DIM: 736
  MAX_DIM: 1792
  NUM_CLASSES: 3
  NUM_FRAMES: 8
MODEL:
  EMBEDDING_DIM_MODE: "xyt"
  USE_SEEDINESS_HEAD: false
  USE_SEMSEG_HEAD: true
TRAINING:
  MODE: "kitti_mots"
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "none"
  MAX_ITERATIONS: 20000
CLUSTERING:
  MIN_SEEDINESS_PROB: 0.95
DATA:
  KITTI_MOTS:
    MAPILLARY_WEIGHT: 0.0
    KITTI_MOTS_WEIGHT: 1.0