INPUT:
  MIN_DIM: 736
  MAX_DIM: 1248
  NUM_CLASSES: 3
  NUM_FRAMES: 8
MODEL:
  EMBEDDING_DIM_MODE: "xyt"
  USE_SEEDINESS_HEAD: false
  USE_SEMSEG_HEAD: true
TRAINING:
  MODE: "kitti_mots"
  INITIAL_LR: 0.001
  LR_DECAY_TYPE: "exponential"
  LR_EXP_DECAY_FACTOR: 0.1
  LR_EXP_DECAY_START: 60000
  LR_EXP_DECAY_STEPS: 20000
  MAX_ITERATIONS: 80000
CLUSTERING:
  MIN_SEEDINESS_PROB: 0.95
DATA:
  KITTI_MOTS:
    MAPILLARY_WEIGHT: 1.0
    KITTI_MOTS_WEIGHT: 0.0